### ISSUE TITLE
CEdit Error When Running species_mass_4.in Verification File

### ISSUE THREAD

**Issue by jrsellers09** [firemodels/cfast#648]
There seems to be a problem when opening the species_mass_4.in verification file.  The following error is obtained in the GUI, however the calculations are not affected by the error:

```
************** Exception Text **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at CEdit.UpdateGUI.VVents(Int32 index)
   at CEdit.CeditMain.VVent_Changed(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at CEdit.UpdateGUI.VVents(Int32 index)
   at CEdit.CeditMain.VVent_Changed(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at CEdit.UpdateGUI.VVents(Int32 index)
   at CEdit.CeditMain.VVent_Changed(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at CEdit.UpdateGUI.VVents(Int32 index)
   at CEdit.CeditMain.UpdateAll()
   at CEdit.CeditMain.OpenDataFile(String FileName)
   at CEdit.CeditMain.Cedit_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CEdit
    Assembly Version: 7.2.1.0
    Win32 Version: 7.2.1.0
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/CEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
C1.Win.C1Report.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.C1Report.4.DLL
----------------------------------------
C1.C1Report.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.C1Report.4.DLL
----------------------------------------
C1.Win.C1DX.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.C1DX.4.DLL
----------------------------------------
C1.Win.C1Document.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.C1Document.4.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
C1.Win.BarCode.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.BarCode.4.DLL
----------------------------------------
C1.Win.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.4.DLL
----------------------------------------
C1.Win.ImportServices.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.ImportServices.4.DLL
----------------------------------------
C1.C1Pdf.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.C1Pdf.4.DLL
----------------------------------------
C1.C1Zip.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.C1Zip.4.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ReachFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/ReachFramework/v4.0_4.0.0.0__31bf3856ad364e35/ReachFramework.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
C1.Win.C1FlexGrid.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.C1FlexGrid.4.DLL
----------------------------------------
NPlot
    Assembly Version: 0.9.10.0
    Win32 Version: 0.9.10.0
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/NPlot.DLL
----------------------------------------
C1.Win.C1Sizer.4
    Assembly Version: 4.0.20161.139
    Win32 Version: 4.0.20161.139
    CodeBase: file:///c:/Program%20Files/firemodels/cfast7/C1.Win.C1Sizer.4.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by rpeacoc** [comment]
I'll take a look and see what's wrong.

**Comment by rpeacoc** [comment]
speciesmass4.in was in a fairly old format for a CFAST input file.  I've corrected CEdit to read these correctly.  A bug fix release will come shortly.  I'll also update all the V&V files to the latest format.
